apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: {{.clusterName}}
    pool: md-0
  name: {{.clusterName}}-md-0
  namespace: {{.eksaSystemNamespace}}
spec:
  clusterName: {{.clusterName}}
  replicas: {{.workerReplicas}}
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: {{.clusterName}}
      pool: md-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: {{.clusterName}}
        pool: md-0
    spec:
      clusterName: {{.clusterName}}
      version: {{.kubernetesVersion}}
      bootstrap:
        configRef:
          name: {{.clusterName}}-md-0
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
      infrastructureRef:
        name: {{.clusterName}}-md-0
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: MicrovmMachineTemplate
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: MicrovmMachineTemplate
metadata:
  name: {{.clusterName}}-md-0
  namespace: {{.eksaSystemNamespace}}
spec:
  template:
    spec:
      vcpu: 2
      memoryMb: 2048
      rootVolume:
        id: root
        image: ghcr.io/richardcase/capmvm-kubernetes:v1.20.11-eks-1-20-10
        mountPoint: "/"
      kernel:
        filename: "boot/vmlinux"
        image: docker.io/richardcase/flintlock-kernel:5.10.77
      kernelCmdline: {}
      networkInterfaces:
      - guestDeviceName: "eth1"
        type: "macvtap"
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: {{.clusterName}}-md-0
  namespace: {{.eksaSystemNamespace}}
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          criSocket: /run/containerd/containerd.sock
          kubeletExtraArgs:
            provider-id: "microvm://{{`{{ ds.meta_data.instance_id }}`}}"
#      users:
#      - name: {{.workerSshUsername}}
#        sshAuthorizedKeys:
#        - '{{.workerSshAuthorizedKey}}'
#        sudo: ALL=(ALL) NOPASSWD:ALL
      format: {{.format}}